/panda1/controller_manager:
  ros__parameters:
    update_rate: 1000  # Hz (Increased from 100 to reduce mimic lag)

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    panda_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    panda_gripper_controller:
      type: position_controllers/GripperActionController

/panda1/panda_arm_controller:
  ros__parameters:
    joints:
      - panda_joint1
      - panda_joint2
      - panda_joint3
      - panda_joint4
      - panda_joint5
      - panda_joint6
      - panda_joint7
    
    command_interfaces:
      - position
    
    state_interfaces:
      - position
      - velocity
    
    state_publish_rate: 50.0
    action_monitor_rate: 20.0
    
    allow_partial_joints_goal: false
    allow_integration_in_goal_trajectories: true
    
    constraints:
      stopped_velocity_tolerance: 0.01
      goal_time: 0.5

/panda1/panda_gripper_controller:
  ros__parameters:
    joint: panda_finger_joint1
    
    action_monitor_rate: 20.0
    
    goal_tolerance: 0.01
    max_effort: 100.0
    
    allow_stalling: false
    stall_velocity_threshold: 0.001
    stall_timeout: 1.0

/panda1/joint_state_broadcaster:
  ros__parameters:
    publish_rate: 50.0

/panda2/controller_manager:
  ros__parameters:
    update_rate: 1000  # Hz (Increased from 100)

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    panda_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    panda_gripper_controller:
      type: position_controllers/GripperActionController

/panda2/panda_arm_controller:
  ros__parameters:
    joints:
      - panda_joint1
      - panda_joint2
      - panda_joint3
      - panda_joint4
      - panda_joint5
      - panda_joint6
      - panda_joint7
    
    command_interfaces:
      - position
    
    state_interfaces:
      - position
      - velocity
    
    state_publish_rate: 50.0
    action_monitor_rate: 20.0
    
    allow_partial_joints_goal: false
    allow_integration_in_goal_trajectories: true
    
    constraints:
      stopped_velocity_tolerance: 0.01
      goal_time: 0.5

/panda2/panda_gripper_controller:
  ros__parameters:
    joint: panda_finger_joint1
    
    action_monitor_rate: 20.0
    
    goal_tolerance: 0.01
    max_effort: 100.0
    
    allow_stalling: false
    stall_velocity_threshold: 0.001
    stall_timeout: 1.0

/panda2/joint_state_broadcaster:
  ros__parameters:
    publish_rate: 50.0
